# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homebrew < Formula
  desc ""
  homepage ""
  version "0.0.4-alpha2"

  on_macos do
    on_intel do
      url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha2/showit_Darwin_x86_64.tar.gz"
      sha256 "13b156ec650a3d1e388d1d371ead4d6fa0991230cfacb6841b46baccc00a93a4"

      def install
        bin.install "showit"
      end
    end
    on_arm do
      url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha2/showit_Darwin_arm64.tar.gz"
      sha256 "da0d2fa25d4d086eb3a04151feaf57dd83eed4bb98d900161ecfcbb6cddb830e"

      def install
        bin.install "showit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha2/showit_Linux_x86_64.tar.gz"
        sha256 "1853a479b662fa7be04c338d5318f141202b658a056402d3057148c43b5c90b4"

        def install
          bin.install "showit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha2/showit_Linux_arm64.tar.gz"
        sha256 "7e4312551fc370390d1c8f8fbd0cf9cb9a7f2816c3a0d2680aa4786d7be187a4"

        def install
          bin.install "showit"
        end
      end
    end
  end
end
