# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellama < Formula
  desc ""
  homepage ""
  version "0.0.1-alpha1"

  on_macos do
    on_intel do
      url "https://github.com/rossedman/shellama/releases/download/v0.0.1-alpha1/shellama_Darwin_x86_64.tar.gz"
      sha256 "5aef46bac0840f1f8951f2ee9eb196e46a245d455a178bec5fe6c7fe9d0d2e59"

      def install
        bin.install "shellama"
      end
    end
    on_arm do
      url "https://github.com/rossedman/shellama/releases/download/v0.0.1-alpha1/shellama_Darwin_arm64.tar.gz"
      sha256 "f44fdb4e882d9554217a6cc6592889b2221aed1eb2c700785686bb5eb22b43e8"

      def install
        bin.install "shellama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/shellama/releases/download/v0.0.1-alpha1/shellama_Linux_x86_64.tar.gz"
        sha256 "588345b379c4ea923663ea87fcf0a6de3670245aca2d75cb639b139cae27a957"

        def install
          bin.install "shellama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/shellama/releases/download/v0.0.1-alpha1/shellama_Linux_arm64.tar.gz"
        sha256 "2dadf5310dc6ddfe931a1db44cfc6bdd96c61d550a4416e46f4200826c581e42"

        def install
          bin.install "shellama"
        end
      end
    end
  end
end
