# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellama < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/rossedman/shellama/releases/download/v0.0.1/shellama_Darwin_x86_64.tar.gz"
      sha256 "0dc5bdb6e05020f57d2df91c974df6dcd3122f4b10e3fd03d79caaf46289aafd"

      def install
        bin.install "shellama"
      end
    end
    on_arm do
      url "https://github.com/rossedman/shellama/releases/download/v0.0.1/shellama_Darwin_arm64.tar.gz"
      sha256 "b7f677e3478244cf4611bceb772c2b8b8be18671926966d2381a6c25bab42bed"

      def install
        bin.install "shellama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/shellama/releases/download/v0.0.1/shellama_Linux_x86_64.tar.gz"
        sha256 "00eb956b35ad69b828a2e66ad498504c59356a3d514b5e8f2711249641dd1f8e"

        def install
          bin.install "shellama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/shellama/releases/download/v0.0.1/shellama_Linux_arm64.tar.gz"
        sha256 "e5b8692e545db0ce7249f6d46fe7b1672ee6f8a1307afd6cd4c94821a66038c3"

        def install
          bin.install "shellama"
        end
      end
    end
  end
end
