# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Showit < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/rossedman/showit/releases/download/v0.0.5/showit_Darwin_x86_64.tar.gz"
      sha256 "67b0cee39057f32f45ef33024dab313317d1317da16d068edd237c7c80efea79"

      def install
        bin.install "showit"
      end
    end
    on_arm do
      url "https://github.com/rossedman/showit/releases/download/v0.0.5/showit_Darwin_arm64.tar.gz"
      sha256 "e7feea29019160a31331bc7169f834585ab8e07e95515b5bfa9fae992b8052d2"

      def install
        bin.install "showit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.5/showit_Linux_x86_64.tar.gz"
        sha256 "13dc99012da23f8a2b74b5276fe426540e37de5255638aa46defe5412a5d802c"

        def install
          bin.install "showit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.5/showit_Linux_arm64.tar.gz"
        sha256 "29f5663b9c93589e8a7e9a58b5432dfdbcb401bb77b8d232fa39ad18eae9144a"

        def install
          bin.install "showit"
        end
      end
    end
  end
end
