# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Showit < Formula
  desc ""
  homepage ""
  version "0.0.4-alpha3"

  on_macos do
    on_intel do
      url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha3/showit_Darwin_x86_64.tar.gz"
      sha256 "fe03648ade0da55ae836289f976e1e4a4f27d71bdeef9776479bb56043006aa2"

      def install
        bin.install "showit"
      end
    end
    on_arm do
      url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha3/showit_Darwin_arm64.tar.gz"
      sha256 "b96eb848d69b1f5cb4f6ec08c4a57799552a9d512089d38bc2cb20cebdcf0cf6"

      def install
        bin.install "showit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha3/showit_Linux_x86_64.tar.gz"
        sha256 "e1201e6a7c8d15df8630bfa466f23c393f7d550ebae653f1d1cb265b5a3a0bbe"

        def install
          bin.install "showit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rossedman/showit/releases/download/v0.0.4-alpha3/showit_Linux_arm64.tar.gz"
        sha256 "4c618368fa08b5b309a3d75cf88cef51747eca3cecb663567844cbd4c8ecc9e3"

        def install
          bin.install "showit"
        end
      end
    end
  end
end
